version: 2.1
orbs:
  github-app-token: ostk0069/github-app-token@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

executors:
  base:
    docker:
      - image: cimg/base:current
  node:
    docker:
      - image: cimg/node:16.19.0
  ruby:
    docker:
      - image: cimg/ruby:3.1.2-node

commands:
  fetch-github-app-token:
    steps:
      # this app is just a tester. this does not have any permission. just generates token.
      - github-app-token/fetch-token:
          app_id: $GITHUB_APP_TOKEN_TESER_ID
          installation_id: 33287507
          base64_private_key: $GITHUB_APP_TOKEN_TESTER_PRIVATE_PEM_BASE64

jobs:
  command-tests:
    parameters:
      run_executor:
        type: executor
        default: base
    executor: << parameters.run_executor >>
    steps:
      - checkout
      - fetch-github-app-token
      - run: echo $GITHUB_APP_TOKEN

workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - command-tests:
          name: command-tests-node
          run_executor: node
          filters: *filters
      - command-tests:
          name: command-tests-ruby
          run_executor: ruby
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ostk0069/github-app-token
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
