version: 2.1
orbs:
  github-app-token: ostk0069/github-app-token@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - github-app-token/fetch-token:
          app_id: $GITHUB_APP_TOKEN_TESER_ID
          installation_id: 33287507
          private_pem: $GITHUB_APP_TOKEN_TESTER_PEM
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ostk0069/github-app-token
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
